### ISSUE TITLE
Prefix VLAN Assignment Validation Incorrect

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-plugin-ssot-infoblox#100]
### Environment
* Python version:  3.7
* Nautobot version:  1.4.2
* nautobot-ssot-infoblox version:  0.7.1

### Expected Behavior
Loading Prefixes without VLANs assigned would be loaded correctly in the Nautobot adapter.

### Observed Behavior
When import Job is ran we get an AttributeError:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 327, in run
    self.sync_data()
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot/jobs/base.py", line 135, in sync_data
    self.load_source_adapter()
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_infoblox/jobs.py", line 94, in load_source_adapter
    self.source_adapter.load()
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_infoblox/diffsync/adapters/nautobot.py", line 205, in load
    self.load_prefixes()
  File "/usr/local/lib/python3.9/site-packages/nautobot_ssot_infoblox/diffsync/adapters/nautobot.py", line 118, in load_prefixes
    vlans={prefix.vlan.vid: prefix.vlan.name} if hasattr(prefix, "vlan") else {},
AttributeError: 'NoneType' object has no attribute 'vid'
```

### Steps to Reproduce
1. Setup Nautobot and Infoblox SSoT.
2. Attempt import with one Prefix that doesn't have a VLAN assigned.
3. See error.

**Comment by jdrew82** [comment]
This is resolved in #101 so closing
