### ISSUE TITLE
Sync between Nautobot and infoblox - KeyError: VLAN>

### ISSUE THREAD

**Issue by Jackass4life** [nautobot/nautobot-plugin-ssot-infoblox#138]
### Environment
* Python version:  Python 3.8.10
* Nautobot version:  1.5.16
* nautobot-ssot-infoblox version:  0.8.0

### Expected Behavior
Sync all data from Infoblox to Nautobot.

### Observed Behavior
When the sync job is started Nautobot have no problems getting the data from Infoblox. But when it get to the "phase" - "Loading data from Nautobot." it failes pretty fast.

When it failes - We then get the following error:
An exception occurred: KeyError: VLAN>
```
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot/jobs/base.py", line 146, in sync_data
    self.load_target_adapter()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_infoblox/jobs.py", line 58, in load_target_adapter
    self.target_adapter.load()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_infoblox/diffsync/adapters/nautobot.py", line 242, in load
    self.load_prefixes()
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_infoblox/diffsync/adapters/nautobot.py", line 143, in load_prefixes
    current_vlans = get_prefix_vlans(prefix=prefix)
  File "/opt/nautobot/lib/python3.8/site-packages/nautobot_ssot_infoblox/utils/nautobot.py", line 31, in get_prefix_vlans
    return [x.destination for x in pf_relations["source"][pf_vlan_relationship]]
KeyError:  VLAN>
```

### Steps to Reproduce
1. Start the sync job to retrieve data from Infoblox.
2. Allow the job to run.
3. Error message "An exception occurred: KeyError: VLAN>" is displayed and the sync job fails.
4. *It is difficult to reproduce the steps when using the plugin and Nautobot out of the box.

I already reached out to JDonga on Slack where we tried the following:
1. Logged into the Nautobot server using nbshell.
2. Ran the following code to check for prefixes without VLAN relationships: 
```
for pf in Prefix.objects.all():
    pf_relations = pf.get_relationships()
    pf_vlan_relationship = Relationship.objects.get(name="Prefix -> VLAN")
    if pf_vlan_relationship not in pf_relations["source"]:
        print(pf.prefix)
```
There where no output.

**Comment by jdrew82** [comment]
@Jackass4life I've gone ahead and pushed a fix for this in the `patch-fix_138` branch. Can you give that a test and see if you're still seeing the issue?

**Comment by qduk** [comment]
Closing as the end user has verified it's been fixed. Thanks Justin!
